[build]
  command = "npm run netlify-build"
  functions = "netlify/functions"
  publish = "."

[dev]
  command = "npm run dev"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  # Route all /api/* requests to the Netlify function
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
